//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @POO2017
//  @ File Name : @BateriaUno
//  @ Date : @12/01/2018
//  @ Author : @Chavez Berumen Anabel
//
//




public class DemoBateriaUno {
	public static void main(String [] args) {
			
			BateriaUno objUno = new BateriaUno();
			int a = 1;
			int b = 2;
			int c = 3;
			int d = -3;
			//Es positivo
			System.out.println("ingreso un numero positivo: " + objUno.esPositivo(a));
			System.out.println("ingreso un numero positivo: " + objUno.esPositivo(d));
			
			//es Mayor 2 variables
			System.out.println("\n¿"+c+ " Es mayor que " +b+  " ?" +objUno.esMayor(c,b));
			System.out.println("¿"+a+ " Es mayor que " +c+  " ?" +objUno.esMayor(a,c));
			System.out.println("¿"+b+ " Es mayor que " +c+  " ?" +objUno.esMayor(b,c));
			
			//es Menor 2 variables
			System.out.println("\n¿"+a+ " Es menor que " +b+  " ?" +objUno.esMenor(a,b));
			System.out.println("¿"+b+ " Es menor que " +a+  " ?" +objUno.esMenor(b,a));
			System.out.println("¿"+b+ " Es menor que " +c+  " ?" +objUno.esMenor(b,c));
			
			//es Igual 2 variables 
			System.out.println("\n¿"+a+ " Es igual que " +b+  " ?" +objUno.esIgual(a,b));
			System.out.println("¿"+a+ " Es igual que " +c+  " ?" +objUno.esIgual(a,c));
			System.out.println("¿"+c+ " Es igual que " +c+  " ?" +objUno.esIgual(c,c));
						
			//Es Mayor con 3 variables y comparación simple			
        	System.out.println("\nel numero mayor es:" +objUno.esMayor(a,b,c));
        	
        	//Calcular numero medio
        	System.out.println("\nEl numero medio es  " +objUno.calcularMedio(a,b,c));
        
        	//Segundos a Horas, minutos y segundos
        	System.out.println("\n El total de horas minutos y segundos es  " +objUno.convertirSegundos(4568));
        	
        	//Determinar dado un numero N sus divisores 
        	System.out.println("\nlos divisores de " +50+ " son: " +objUno.divisor(50));
        	
        	//Suma de los numeros enteros entre 1 y N enteros dados
        	System.out.println("\nLa suma de los numeros de 1 hasta " +50+" son: "+objUno.sumaEnteros(50));
        	
        	//Suma de los numeros enteros pares entre 1 y N enteros dados
        	System.out.println("\nLa suma de los numeros pares de 1 hasta " +50+" son: "+objUno.sumaPar(50));
        	
        	//Suma de los numeros enteros impares entre 1 y N enteros dados
        	System.out.println("\nLa suma de los numeros impares de 1 hasta " +50+" son: "+objUno.sumaImpar(50));
        	
        	//Calcular el promedio de los numeros pares entre 1 y N enteros dados
        	System.out.println ("\nEl promedio de los numeros pares entre 1 y " +100+ " es : "+objUno.promedioPares(100));
        	
        	//Calcular el promedio de los numeros impares entre 1 y N enteros dados
        	System.out.println ("\nEl promedio de los numeros impares entre 1 y " +100+ "es : "+objUno.promedioImpares(100));
        	
        	//Tabla de multiplicar
        	System.out.println ("\n La tabla de multiplicar de el numero "+7+ " es : "+objUno.tablaMultiplicar(7));
        	
        	//Calcular el factorial de un numero mayor o igual a 0 dado;
        	System.out.println ("\n El factorial de "+ 10 + " es : "+objUno.factorial(10));
        	
        	//Determinar si un numero es primo
        	System.out.println ("\n ¿El numero " + 12+ " es primo?"+objUno.esPrimo(12));
        	System.out.println ("\n ¿El numero " + 37+ " es primo?"+objUno.esPrimo(37));        	
        	
        	//Dado un valor base y un valor exponente determinar la potencia
        	System.out.println ("\n La potencia de 6^7 es: "+objUno.potencia(6,7));
        	
        	
        	
        	
        	
	}
}
